# Generated by Django 4.0.5 on 2022-06-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kurs Adı Giriniz', max_length=100, unique=True, verbose_name='Kurs Adı')),
                ('description', models.TextField(help_text='Kurs Açıklaması Giriniz', max_length=1000, verbose_name='Açıklama')),
                ('image', models.ImageField(default='courses/placeholder-image.jpg', upload_to='courses/%Y/%m/%d')),
                ('date', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True, verbose_name='Yayın')),
            ],
        ),
    ]
