# Generated by Django 4.0.5 on 2022-06-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_height_alter_course_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='height',
        ),
        migrations.RemoveField(
            model_name='course',
            name='width',
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/placeholder-image.jpg', upload_to='courses/%Y/%m/%d'),
        ),
    ]
